num_agents: 2
# initial_mdp_states: []
initial_rm_states: 
  # - [4, 1]
  # - [8, 12]
  # - [15, 21]
  # - [22, 23]
labeled_mdp_class: "OvercookedCircuitLabeled"
max_episode_length: 400
eval_freq: 5000
gamma: 0.98
forbidden_events:
  - []
  - []
required_events:
  - ['c']
  - ['c']
ucb_c: 0.5