num_agents: 2
# initial_mdp_states: []
initial_rm_states: 
  - [1, 4]
  - [8, 12]
  - [15, 21]
  - [22, 23]
labeled_mdp_class: "OvercookedCustomIslandLabeled"
max_episode_length: 400
eval_freq: 1000000
gamma: 0.9