num_agents: 2
# initial_mdp_states: []
initial_rm_states:
  - [2, 3]
  # - [12, 8]
  # - [4, 1]
  # - [15, 21]
  # - [22, 23]
forbidden_events:
  - []
  - []
required_events:
  - ['c']
  - ['c']
labeled_mdp_class: "OvercookedCustomIslandLabeled"
max_episode_length: 200
eval_freq: 10000
gamma: 0.96
ucb_c: 0.5
ent_coef: 0.01