num_agents: 2
# initial_mdp_states: []
initial_rm_states:
  - [1, 2]
  # - [8, 12]
  # - [15, 21]
  # - [22, 23]
forbidden_events:
  - []
  - []
required_events:
  - ['c']
  - ['c']
labeled_mdp_class: "OvercookedInterestingCrampedLabeled"
max_episode_length: 400
eval_freq: 2000
gamma: 0.99
ucb_c: 0.5
ent_coef: 0.001
ucb_gamma: 1