program: run.py
method: grid  # Use grid search to test all combinations
parameters:
  add_mono_file:
    values: ["None"]  # Replace with your specific file names
  handpicked_decomp:
    values: ["None"]  # Replace with your specific file names
  num_candidates:
    values: [0]
  seed:
    values: [1, 2, 3, 4, 5]
  env:
    values: ["overcooked"]
  decomposition_file:
    values: ["individual_custom_island.txt"]
  assignment_methods:
    values: ["ground_truth"]
  num_iterations:
    values: [1]
  wandb:
    values: [True]
  sweep:
    values: [True]
  experiment_name:
    values: ["custom_island"]
  is_monolithic:
    values: [False]
  render:
    values: [False]
  video:
    values: [False]
  timesteps:
    values: [1000000]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}

# --env buttons
# python run.py --assignment_methods UCB --num_iterations 1 --wandb f 
# --decomposition_file mono_challenge_buttons.txt --experiment_name buttons_challenge 
# --is_monolithic f --env buttons --render f --video f --add_mono_file mono_challenge_buttons.txt 
# # --num_candidates 10  --timesteps 3000000 --handpicked_decomp aux_buttons.txt
# Include other necessary arguments with default values or placeholders