num_agents: 2
max_episode_length: 100
initial_mdp_states: [0, 9]
initial_rm_states:
  - [1, 2]
  - [6, 8]
  - [11, 13]
gamma: 0.95
learning_rate: 0.0005
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: 0.1
ent_coef: 0.1
labeled_mdp_class: "HardButtonsLabeled"

# num_agents: 2
# max_episode_length: 100
# initial_mdp_states: [0, 9]
# initial_rm_states:
#   - [1, 2]
#   - [6, 8]
#   - [11, 13]
# gamma: 0.95
# learning_rate: 0.0005
# vf_coef: 10
# max_grad_norm: 10
# target_kl: 0.05
# ent_coef: 0.1
# labeled_mdp_class: "HardButtonsLabeled"
