# initial_mdp_states: [0, 5, 9]
# max_episode_length: 1000
# initial_rm_states: [1,3,5]
joint_rm_file: "buttons_aux_rm.txt"
team_rm_file: "team_buttons_rm.txt"
manager_epsilon: 1
manager_epsilon_decay: 0.95
manager_assignment_method: "multiply"

#real fields
initial_rm_states: [1, 3, 5]
initial_mdp_states: [0, 5, 9]
max_episode_length: 1000