# Ground truth + multiply work
num_agents: 3
max_episode_length: 400
initial_mdp_states: [0, 5, 8]
initial_rm_states:
  - [1, 5, 12]
gamma: 0.95
learning_rate: 0.0005
vf_coef: 10
max_grad_norm: 10
target_kl: 0.05
ent_coef: 0.1
labeled_mdp_class: "EasyButtonsLabeled"
eval_freq: 5000