# Ground truth + multiply work
num_agents: 3
max_episode_length: 100
initial_mdp_states: [0, 5, 8]
initial_rm_states:
  - [1,2,3] # monolithic trial start states
forbidden_events:
  - ['a2br', 'a3br', 'a2lr', 'a3lr']
  - ['a3br', 'a3lr']
  - ['a2br', 'a2lr']
required_events:
  - []
  - []
  - []
gamma: 0.95
learning_rate: 0.0005
vf_coef: 10
max_grad_norm: 10
target_kl: 0.05
ent_coef: 0.1
labeled_mdp_class: "EasyButtonsLabeled"
eval_freq: 10000